organism: mus_musculus
census_version: 2024-07-01
ref_keys: [subclass, class, family, global]
subsample_ref: 50
cutoff: 0.75
remove_unknown: true
ref_split: dataset_id
ref_collections: [A taxonomy of transcriptomic cell types across the isocortex and hippocampal formation, An integrated transcriptomic and epigenomic atlas of mouse primary motor cortex cell types, Tabula Muris Senis]
integration_method: pcaproject
dims: 50
max_features: 200
k_anchor: 10
k_score: 30
k_weight: 50
outdir: /space/grp/rschwartz/rschwartz/eval-references/2024-07-01/mus_musculus/dataset_id/SCT/gap_false/ref_50
normalization_method: SCT
subset_type: sample
batch_correct: true
nmads: 5
use_gap: false
